export const SEARCH_DATA_FETCHED = "SEARCH_DATA_FETCHED";
export const IS_FETCHING_SEARCH_DATA = "IS_FETCHING_SEARCH_DATA";
export const FETCHING_SEARCH_DATA_FAILURE = "FETCHING_SEARCH_DATA_FAILURE";
